# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: decisions.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'decisions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from auditor.proto_gen import events_pb2 as events__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x65\x63isions.proto\x12\nauditor.v1\x1a\x0c\x65vents.proto\"K\n\x13GateDecisionRequest\x12 \n\x05\x65vent\x18\x01 \x01(\x0b\x32\x11.auditor.v1.Event\x12\x12\n\ntimeout_ms\x18\x02 \x01(\x05\"|\n\x14GateDecisionResponse\x12\x13\n\x0b\x64\x65\x63ision_id\x18\x01 \x01(\t\x12*\n\x08\x64\x65\x63ision\x18\x02 \x01(\x0e\x32\x18.auditor.v1.GateDecision\x12\x0f\n\x07reasons\x18\x03 \x03(\t\x12\x12\n\nlatency_ms\x18\x04 \x01(\x05\"=\n\tHeartbeat\x12\x12\n\nts_unix_ns\x18\x01 \x01(\x03\x12\x0e\n\x06run_id\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"$\n\rSeccompUpdate\x12\x13\n\x0bpolicy_json\x18\x01 \x01(\t\"\xef\x01\n\x05\x46rame\x12\"\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x11.auditor.v1.EventH\x00\x12.\n\x03req\x18\x02 \x01(\x0b\x32\x1f.auditor.v1.GateDecisionRequestH\x00\x12\x30\n\x04resp\x18\x03 \x01(\x0b\x32 .auditor.v1.GateDecisionResponseH\x00\x12#\n\x02hb\x18\x04 \x01(\x0b\x32\x15.auditor.v1.HeartbeatH\x00\x12\x33\n\x0eseccomp_update\x18\x05 \x01(\x0b\x32\x19.auditor.v1.SeccompUpdateH\x00\x42\x06\n\x04kind*J\n\x0cGateDecision\x12\x18\n\x14\x44\x45\x43ISION_UNSPECIFIED\x10\x00\x12\t\n\x05\x41LLOW\x10\x01\x12\x08\n\x04\x44\x45NY\x10\x02\x12\x0b\n\x07\x43ONFIRM\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'decisions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GATEDECISION']._serialized_start=591
  _globals['_GATEDECISION']._serialized_end=665
  _globals['_GATEDECISIONREQUEST']._serialized_start=45
  _globals['_GATEDECISIONREQUEST']._serialized_end=120
  _globals['_GATEDECISIONRESPONSE']._serialized_start=122
  _globals['_GATEDECISIONRESPONSE']._serialized_end=246
  _globals['_HEARTBEAT']._serialized_start=248
  _globals['_HEARTBEAT']._serialized_end=309
  _globals['_SECCOMPUPDATE']._serialized_start=311
  _globals['_SECCOMPUPDATE']._serialized_end=347
  _globals['_FRAME']._serialized_start=350
  _globals['_FRAME']._serialized_end=589
# @@protoc_insertion_point(module_scope)
