# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: verdicts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'verdicts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0everdicts.proto\x12\nauditor.v1\"\x9b\x02\n\x07Verdict\x12\x12\n\nverdict_id\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\x12\x11\n\ttenant_id\x18\x03 \x01(\t\x12\x10\n\x08\x64\x65tector\x18\x04 \x01(\t\x12\x14\n\x0c\x61si_category\x18\x05 \x01(\t\x12)\n\x06result\x18\x06 \x01(\x0e\x32\x19.auditor.v1.VerdictResult\x12\x12\n\nconfidence\x18\x07 \x01(\x01\x12\x15\n\revidence_json\x18\x08 \x01(\t\x12\x13\n\x0bjudge_model\x18\t \x01(\t\x12\x16\n\x0ejudge_prompt_v\x18\n \x01(\x05\x12\x1a\n\x12rubric_scores_json\x18\x0b \x01(\t\x12\x12\n\nts_unix_ns\x18\x0c \x01(\x03\"\xbb\x01\n\x04\x46lag\x12\x0f\n\x07\x66lag_id\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\x12\x11\n\ttenant_id\x18\x03 \x01(\t\x12&\n\x08severity\x18\x04 \x01(\x0e\x32\x14.auditor.v1.Severity\x12\x16\n\x0e\x61si_categories\x18\x05 \x03(\t\x12\x13\n\x0bverdict_ids\x18\x06 \x03(\t\x12\x0e\n\x06status\x18\x07 \x01(\t\x12\x1a\n\x12\x63reated_at_unix_ns\x18\x08 \x01(\x03*X\n\rVerdictResult\x12\x1e\n\x1aVERDICT_RESULT_UNSPECIFIED\x10\x00\x12\r\n\tVIOLATION\x10\x01\x12\x06\n\x02OK\x10\x02\x12\x10\n\x0cNEEDS_REVIEW\x10\x03*Q\n\x08Severity\x12\x18\n\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x07\n\x03LOW\x10\x01\x12\n\n\x06MEDIUM\x10\x02\x12\x08\n\x04HIGH\x10\x03\x12\x0c\n\x08\x43RITICAL\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'verdicts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERDICTRESULT']._serialized_start=506
  _globals['_VERDICTRESULT']._serialized_end=594
  _globals['_SEVERITY']._serialized_start=596
  _globals['_SEVERITY']._serialized_end=677
  _globals['_VERDICT']._serialized_start=31
  _globals['_VERDICT']._serialized_end=314
  _globals['_FLAG']._serialized_start=317
  _globals['_FLAG']._serialized_end=504
# @@protoc_insertion_point(module_scope)
